### ISSUE TITLE
CartoDB visualization not working when CartoDB account has an organization

### ISSUE THREAD

**Issue by matallo** [CartoDB/odyssey.js#189]

**Comment by matallo** [comment]
can't reproduce, closing

**Comment by allthesignals** [comment]
I've switched my tables to public and I can't seem to use organization maps. Here's my code:
`-vizjson: "http://mapc.cartodb.com/u/mapc-admin/api/v2/viz/0a600d70-7f47-11e6-ba9c-0e3ebc282e83/viz.json"`

The tile urls look like this:
`http://3.api.cartocdn.com/mapc-admin/api/v1/map/undefined/9/83/196.png` which returns a 400 from carto
