### ISSUE TITLE
Error: Column "points_density" does not exist, showing a density map

### ISSUE THREAD

**Issue by jorgeas80** [CartoDB/odyssey.js#196]
Created a odyssey map, loading a visualization based on a density map. Got this error:

`Postgis Plugin: ERROR: column "points_density" does not exist LINE 1: ...ify("the_geom_webmercator", 6.74483e-06)) AS geom,"points_de... ^ in executeQuery Full sql was: 'SELECT ST_AsBinary(ST_Simplify("the_geom_webmercator", 6.74483e-06)) AS geom,"points_density" FROM (SELECT * FROM mallorca_points_to_heatmap) as cdbq WHERE "the_geom_webmercator" && ST_SetSRID('BOX3D(-20037508.3 20037508.29613578,-20037508.29613578 20037508.3)'::box3d, 3857)' `

You can click [here](http://jorgearevalo.cartodb.com/api/v1/map?stat_tag=2d5d12d6-a22c-11e4-9569-0e018d66dc29&config=%7B%22version%22%3A%221.0.1%22%2C%22stat_tag%22%3A%222d5d12d6-a22c-11e4-9569-0e018d66dc29%22%2C%22layers%22%3A%5B%7B%22type%22%3A%22cartodb%22%2C%22options%22%3A%7B%22sql%22%3A%22SELECT%20*%20FROM%20mallorca_points_to_heatmap%22%2C%22cartocss%22%3A%22%2F**%20density%20visualization%20*%2F%5Cn%5Cn%23mallorca_points_to_heatmap%7B%5Cn%20%20polygon-fill%3A%20%23B10026%3B%5Cn%20%20polygon-opacity%3A%200.8%3B%5Cn%20%20line-color%3A%20%23FFF%3B%5Cn%20%20line-width%3A%200%3B%5Cn%20%20line-opacity%3A%200%3B%5Cn%7D%5Cn%23mallorca_points_to_heatmap%7B%5Cn%20%20%5Bpoints_density%20%3C%3D%200.0000658292726750842%5D%20%7B%20polygon-fill%3A%20%23B10026%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.0000202551608231028%5D%20%7B%20polygon-fill%3A%20%23E31A1C%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.0000131658545350168%5D%20%7B%20polygon-fill%3A%20%23FC4E2A%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.00000708930628808599%5D%20%7B%20polygon-fill%3A%20%23FD8D3C%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.00000202551608231028%5D%20%7B%20polygon-fill%3A%20%23FEB24C%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.00000101275804115514%5D%20%7B%20polygon-fill%3A%20%23FED976%3B%20%20%7D%5Cn%20%20%5Bpoints_density%20%3C%3D%200.00000101275804115514%5D%20%7B%20polygon-fill%3A%20%23FFFFB2%3B%20%20%7D%5Cn%5Cn%7D%22%2C%22cartocss_version%22%3A%222.1.1%22%7D%7D%5D%7D&callback=_cdbc_1205317822_1) to see the error live

**Comment by matallo** [comment]
this is not an odyssey issue

does mallorca_points_to_heatmap exist in your mallorca_points_to_heatmap table?

**Comment by jorgeas80** [comment]
The table mallorca_points_to_heatmap does exist, but looks like the query is trying to access a field "points_density" in that table. That field doesn't exist.
